import { useEffect, useState } from 'react'
import { ExternalLink, FileText, Folder, FolderOpen, Link2, Pencil, Plus, RotateCcw, Search, Sparkles, Trash2, Upload } from 'lucide-react'
import { service } from './service'
import { roleLabels } from './types'
import type { Course, FileAsset, ModuleDescriptor, Provider, Settings, Snapshot } from './types'
import { errorText, fileName, fullDate } from './ui'

export function FilesPage({ snapshot, onRelink, onOpenAssignment, onUndo }: { snapshot: Snapshot; onRelink: (file: FileAsset) => void; onOpenAssignment: (id: string) => void; onUndo: (id: string) => void }) {
  const [query, setQuery] = useState('')
  const [missingOnly, setMissingOnly] = useState(false)
  const [typeFilter, setTypeFilter] = useState('')
  const [courseFilter, setCourseFilter] = useState('')
  const usedFiles = snapshot.files.filter(file => snapshot.links.some(link => link.file_id === file.id) || snapshot.common_files.some(item => item.file_id === file.id))
  const courseIds = (id: string) => [...new Set([...snapshot.common_files.filter(item => item.file_id === id).map(item => item.course_id), ...snapshot.links.filter(link => link.file_id === id).map(link => snapshot.assignments.find(item => item.id === link.assignment_id)?.course_id || '')])]
  const typeOf = (path: string) => { const ext = path.split('.').at(-1)?.toLowerCase(); return ext === 'pdf' ? 'pdf' : ['doc','docx'].includes(ext || '') ? 'word' : ['png','jpg','jpeg','webp','gif','bmp','tif','tiff'].includes(ext || '') ? 'image' : 'other' }
  const visible = usedFiles.filter(file => (!missingOnly || file.missing) && (!typeFilter || typeOf(file.path) === typeFilter) && (!courseFilter || courseIds(file.id).includes(courseFilter)) && file.path.toLowerCase().includes(query.toLowerCase()))
  return <><div className="page-header"><div><h1>文件</h1><p>{usedFiles.length} 个已关联文件 · {usedFiles.filter(f => f.missing).length} 个链接待修复</p></div></div><div className="file-page-toolbar"><div className="search-field"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索文件名或路径" /></div><select aria-label="按文件类型筛选" value={typeFilter} onChange={e => setTypeFilter(e.target.value)}><option value="">全部类型</option><option value="pdf">PDF</option><option value="word">Word 文档</option><option value="image">图片</option><option value="other">其他</option></select><select aria-label="按科目筛选" value={courseFilter} onChange={e => setCourseFilter(e.target.value)}><option value="">全部科目</option>{snapshot.courses.map(course => <option key={course.id} value={course.id}>{course.name}</option>)}</select><label className="checkbox-label"><input type="checkbox" checked={missingOnly} onChange={e => setMissingOnly(e.target.checked)} />仅显示失效链接</label></div><div className="file-page-list">{visible.map(file => { const links = snapshot.links.filter(link => link.file_id === file.id); return <div className="file-page-row" key={file.id}><div className={`file-page-icon ${file.missing ? 'missing' : ''}`}><FileText size={21} /></div><div className="file-page-main"><strong>{fileName(file.path)}</strong><small title={file.path}>{file.path}</small><div className="file-relations">{links.map(link => <button key={link.id} onClick={() => onOpenAssignment(link.assignment_id)}>{snapshot.assignments.find(a => a.id === link.assignment_id)?.title || '未知作业'} · {roleLabels[link.role]}</button>)}{courseIds(file.id).map(id => { const course = snapshot.courses.find(c => c.id === id); return course ? <span className="file-course-tag" key={id}>{course.name}</span> : null })}</div></div><div className="file-page-actions">{file.missing ? <button className="button button-quiet" onClick={() => onRelink(file)}><Link2 size={16} />重新定位</button> : <button className="icon-button" onClick={() => { void service.openFile(file.id).catch(e => window.alert(`打开文件失败：${errorText(e)}`)) }} title="打开文件"><ExternalLink size={17} /></button>}</div></div> })}{!visible.length ? <div className="empty-list"><FolderOpen size={30} /><strong>没有找到关联文件</strong><span>在作业详情中添加题目材料或解答。</span></div> : null}</div><section className="history-section"><h2>改名历史</h2><p>只有最近一次仍有效的改名可以撤回；文件被外部修改后会阻止撤回。</p>{snapshot.renames.map(event => <div className="history-row" key={event.id}><RotateCcw size={17} /><div><strong>{fileName(event.new_path)}</strong><small>原名：{fileName(event.old_path)} · {fullDate(event.changed_at)}</small></div>{event.undone_at ? <span className="muted">已撤回</span> : <button className="button button-quiet" onClick={() => onUndo(event.id)}>撤回</button>}</div>)}{!snapshot.renames.length ? <div className="history-empty">尚无改名记录</div> : null}</section></>
}

export function SettingsPage({ snapshot, onSaveSettings, onAddProvider, onEditProvider, onDeleteProvider, onEditCourse, onAddSemester, onBackup, onRestore }: { snapshot: Snapshot; onSaveSettings: (value: Settings) => void; onAddProvider: () => void; onEditProvider: (provider: Provider) => void; onDeleteProvider: (id: string) => void; onEditCourse: (course: Course) => void; onAddSemester: () => void; onBackup: () => void; onRestore: () => void }) {
  const [settings, setSettings] = useState(snapshot.settings)
  const [promptPath, setPromptPath] = useState('')
  const [modules, setModules] = useState<ModuleDescriptor[]>([])
  const [modulePath, setModulePath] = useState('')
  useEffect(() => setSettings(snapshot.settings), [snapshot.settings])
  useEffect(() => { void service.promptDirectory().then(setPromptPath).catch(() => {}); void service.modulesDirectory().then(setModulePath).catch(() => {}); void service.listModules().then(setModules).catch(() => {}) }, [])
  const update = (patch: Partial<Settings>) => setSettings(current => ({ ...current, ...patch }))
  return <><div className="page-header"><div><h1>设置</h1><p>管理课程目录、命名规则、功能模块、云端模型和数据库备份</p></div></div><div className="settings-layout"><section className="settings-card"><div className="settings-card-title"><div><h2>外观与文件命名</h2><p>只影响应用显示和手动执行的原地重命名。</p></div></div><div className="form-grid"><label className="form-field">界面主题<select value={settings.theme} onChange={e => update({ theme:e.target.value as Settings['theme'] })}><option value="light">浅色</option><option value="dark">中性深灰</option></select></label><label className="form-field span-2">命名模板<input value={settings.naming_template} onChange={e => update({ naming_template:e.target.value })} /></label></div><p className="helper-text">可用字段：{'{course_code}'}、{'{material}'}、{'{scope}'}（s 节或 ch 章）；兼容 {'{sections}'}；也兼容 {'{semester}'}、{'{course}'}、{'{assignment}'}、{'{role}'}、{'{version}'}。原文件扩展名会保留。</p><button className="button button-primary" onClick={() => onSaveSettings(settings)}>保存设置</button></section>
    <section className="settings-card"><div className="settings-card-title"><div><h2>AI 服务商</h2><p>只有点击“开始识别”才会发送本次输入。密钥保存在 Windows 凭据管理器。</p></div><button className="button button-quiet" onClick={onAddProvider}><Plus size={16} />添加服务商</button></div>{snapshot.providers.map(provider => <div className="provider-row" key={provider.id}><div className="provider-icon"><Sparkles size={19} /></div><div><strong>{provider.name}</strong><small>{provider.model} · {provider.has_key ? '密钥已保存' : '未保存密钥'}</small></div><button className="icon-button" onClick={() => onEditProvider(provider)} title="编辑"><Pencil size={16} /></button><button className="icon-button danger-hover" onClick={() => onDeleteProvider(provider.id)} title="删除"><Trash2 size={16} /></button></div>)}{!snapshot.providers.length ? <div className="settings-empty">尚未配置 AI 服务商。手动录入与文件管理仍可使用。</div> : null}<div className="form-grid provider-routing"><label className="form-field">作业识别使用<select value={settings.assignment_provider_id} onChange={e => update({ assignment_provider_id:e.target.value })}><option value="">未指定</option>{snapshot.providers.map(p => <option value={p.id} key={p.id}>{p.name} · {p.model}</option>)}</select></label><label className="form-field">教材匹配使用 <small>未来功能</small><select value={settings.material_provider_id} onChange={e => update({ material_provider_id:e.target.value })}><option value="">未指定</option>{snapshot.providers.map(p => <option value={p.id} key={p.id}>{p.name} · {p.model}</option>)}</select></label></div><button className="button button-primary" onClick={() => onSaveSettings(settings)}>保存模型分配</button></section>
    <section className="settings-card"><div className="settings-card-title"><div><h2>AI 提示词文件</h2><p>每次识别时读取本地文件；修改后无需重启。请保留模板中的占位符。</p></div></div><p className="helper-text">{promptPath || '加载中…'}</p><p className="helper-text">assignment_system.txt 与 assignment_user.txt。用户提示词必须包含 {'{content}'}。</p><button className="button button-quiet" onClick={() => { void service.openPromptDirectory().catch(e => window.alert(`打开提示词文件夹失败：${errorText(e)}`)) }}><FolderOpen size={16} />打开提示词文件夹</button></section>
    <section className="settings-card"><div className="settings-card-title"><div><h2>学期与课程目录</h2><p>文件仍在原位置；目录用于按课程浏览和搜索。</p></div><button className="button button-quiet" onClick={onAddSemester}><Plus size={16} />添加学期</button></div>{snapshot.semesters.map(semester => <div className="semester-settings" key={semester.id}><strong>{semester.name}</strong><small>{semester.source_root || '未关联学期根目录'}</small>{snapshot.courses.filter(c => c.semester_id === semester.id).map(course => <button key={course.id} className="course-settings-row" onClick={() => onEditCourse(course)}><Folder size={17} /><span>{course.name}<small>{course.folder_path || '未关联文件夹'}</small></span><Pencil size={15} /></button>)}</div>)}</section>
    <section className="settings-card"><div className="settings-card-title"><div><h2>数据库备份</h2><p>备份作业、关联路径、常用文件、自定义字段、设置和改名历史；不包含实际文件、提示词文件或 API 密钥。</p></div></div><div className="backup-buttons"><button className="button button-quiet" onClick={onBackup}><Upload size={16} />导出备份</button><button className="button button-quiet" onClick={onRestore}><RotateCcw size={16} />从备份恢复</button><button className="button button-quiet" onClick={() => { void service.compactDatabase().then(() => window.alert("数据库已压缩")).catch(e => window.alert(`压缩失败：${errorText(e)}`)) }}>压缩数据库</button></div></section><section className="settings-card"><div className="settings-card-title"><div><h2>功能模块</h2><p>内置模块和本地安装模块使用相同的能力接口；外部模块仅在调用时运行。</p></div></div>{modules.map(module => <div className="module-row" key={module.id}><strong>{module.name} · {module.builtin ? "内置" : "外部"}</strong><small>v{module.version} · {module.capabilities.join("、")}</small></div>)}<p className="helper-text">模块目录：{modulePath || "加载中…"}</p><div className="backup-buttons"><button className="button button-quiet" onClick={() => { void service.openModulesDirectory().catch(e => window.alert(errorText(e))) }}><FolderOpen size={16} />打开模块目录</button><button className="button button-quiet" onClick={() => { void service.listModules().then(setModules).catch(e => window.alert(errorText(e))) }}>刷新模块</button></div></section></div></>
}
